retire license category reporting
nexB/deltacode pull request #116
Opened 2019-03-29 18:35 UTC by iamsid2

Tried to solve issue[106](https://github.com/nexB/deltacode/issues/106)
Signed-off-by: iamsid2 <shaktimund97@gmail.com>

2019-03-29 19:08 UTC, steven-esser requested changes
You have a number of failing tests. Please fix these. 

You can run the test suite locally via `py.test`.

2019-03-29 19:08 UTC, majurg commented on src/deltacode/utils.py
> +    # old_categories = set(license.category for license in old_licenses)
Delete these lines instead of adding comments

2019-03-29 19:08 UTC, majurg commented on src/deltacode/utils.py
> +        #         delta.update(0, category.lower() + ' added')
Same thing here, see above comments

2019-03-29 19:08 UTC, majurg commented on src/deltacode/utils.py
> +        #         delta.update(0, category.lower() + ' added')
Same comment as above

2019-03-30 06:56 UTC, iamsid2 commented
yeah working on it now.

2019-03-30 08:24 UTC, iamsid2 commented
Looks like there is a clash between python 3.6 and 2.7 as i have anaconda installed which as python 3.6 as its root

2019-04-01 16:35 UTC, majurg commented
@iamsid2 Currently, DeltaCode uses python2.7.

2021-03-18 19:55 UTC, majurg commented
Closing due to stagnation.

2021-03-18 19:55 UTC, closed without merging