added the windows build for travis CI having py2 interpreter
nexB/deltacode pull request #152
Opened 2020-04-02 06:08 UTC by Pratikrocks

added the windows build to travis CI having py2 as interpreter

2020-04-02 06:29 UTC, Pratikrocks commented on .travis.yml
> +        - choco install python2 -x86
`choco install python2 -x86` installs `32 bit libs` in a `32 bit` system.
without `-x86` it installs `64 bit libs ` also which causes error during configuration.

2020-04-02 06:39 UTC, Pratikrocks commented on .travis.yml
> +        - ln -s /c/Python27/python.exe /c/Python27/python2.7.exe
We need to create a soft link pointing to `/c/Python27/python.exe` as during the configuration it will point to this executable file.

2020-04-02 06:41 UTC, Pratikrocks commented on src/deltacode/test_utils.py
> -
Currently we do not have the support for adding the cli option --timeout, we may require it for the Appevyor windows CI as it timesout after 120 sec.

2020-04-02 12:35 UTC, Pratikrocks commented
@majurg the windows build is working.

2020-04-02 16:03 UTC, steven-esser requested changes
Have you reviewed how this is done for `scancode-toolkit`?

2020-04-02 16:13 UTC, Pratikrocks commented
> Have you reviewed how this is done for `scancode-toolkit`?

@majurg `scancode -toolkit ` is using osx and linux build in its TravisCi

2020-04-02 16:25 UTC, Pratikrocks commented
> Have you reviewed how this is done for `scancode-toolkit`?

@majurg sorry I couldn't get you.
What do I need to be reviewed?

2020-04-12 19:34 UTC, Pratikrocks commented
@majurg , should I need to make any additional changes in this windows build?

2020-04-13 22:46 UTC, steven-esser requested changes
I am not sure we actually want windows builds in Travis CI. We probably want them in Appveryor like scancode-toolkit does.

2020-04-14 04:31 UTC, Pratikrocks commented
@majurg I will be adding the windows build for appveyor , I am closing this PR for now as it is not required , I will re - open it whenever needed

2020-04-14 04:31 UTC, closed without merging