Documentation changes
nexB/deltacode pull request #168
Opened 2021-06-28 14:04 UTC by Pratikrocks

This  PR is meant for updating the documentation at various locations in the codebase, as well as adding/updating an extensive docs in `ReadTheDocs` owing to the changes due to integration of the `VirtualCodebase`

Signed-off-by: Pratik Dey <pratikrocks.dey11@gmail.com>

2021-06-30 13:07 UTC, majurg approved these changes

2021-07-15 14:49 UTC, majurg requested changes
I think this just needs to be rebased with main; but this can be merged right after.

2021-07-15 14:51 UTC, Pratikrocks commented
Yes we need to rebase it , and some modifications are required to in this PR

2021-08-13 18:53 UTC, Pratikrocks commented on docs/source/deltacode/comprehensive_installation.rst
> +Using the docker image for testing Deltacode
This is the required instructions to run the docker image

2021-08-18 16:33 UTC, AyanSinhaMahapatra commented
@Pratikrocks does this replace the absolete docs at https://github.com/nexB/aboutcode/tree/master/docs/source/deltacode?

2021-08-18 16:34 UTC, Pratikrocks commented
Yes it replaces the old one

2021-08-18 16:34 UTC, Pratikrocks commented
Though the GSOC work report(.rst) is not present here

2021-08-18 16:37 UTC, AyanSinhaMahapatra commented
Right, then you could open a PR deleting them at https://github.com/nexB/aboutcode/tree/master/docs/source/deltacode and [here](https://github.com/nexB/aboutcode/blob/master/docs/source/index.rst#aboutcode-project-docs) link to the new docs.

2021-08-18 16:41 UTC, Pratikrocks commented
Alright I am doing it

2021-08-18 17:34 UTC, Pratikrocks commented on docs/source/deltacode/GSOC_2021_report.rst
> +Google Summer of Code 2021 - Final report
added the .rst here @AyanSinhaMahapatra

2021-08-20 18:39 UTC, AyanSinhaMahapatra commented on docs/source/deltacode/GSOC_2021_report.rst
> +Google Summer of Code 2021 - Final report
LGTM

2022-03-11 09:32 UTC, pombredanne approved these changes

2022-03-11 09:34 UTC, merged