added docker file
nexB/deltacode pull request #178
Opened 2021-07-22 13:22 UTC by Pratikrocks

Added `DockerFile`  `docker-compose.yml` 
 
Signed-off-by: Pratik Dey <pratikrocks.dey11@gmail.com>

2021-08-07 21:53 UTC, majurg requested changes
Can you write a bit of documentation as to how to go about using deltacode with Docker? So simple examples would be nice

2021-08-08 00:28 UTC, Pratikrocks commented
Okay then i am adding in the RTD related Pr

2021-08-13 18:51 UTC, Pratikrocks commented
@majurg I updated the usages in this PR https://github.com/nexB/deltacode/pull/168

2021-08-16 14:44 UTC, pombredanne commented on docker-compose.yml
> +# http://nexb.com and https://github.com/nexB/scancode.io
I reckon you copied this from ScanCode.io... but there is no need to carry the scancode.io references

2021-08-26 09:54 UTC, ddmesh commented on docker-compose.yml
> +# http://nexb.com and https://github.com/nexB/scancode.io
This also should be changed in Dockerfile not just here in docker-compose.yml. There are other references to scancode.io too in the comments of both files that should be adapted.
It would be nice to have those changes soon and merged, as I would like to update my local installation and avoid creating my own Dockerfile locally.
Thanks a lot.

2021-08-26 10:48 UTC, pratik0316 commented on docker-compose.yml
> +# http://nexb.com and https://github.com/nexB/scancode.io
@pombredanne , @ddmesh I changed those licenses Thanks :)

2021-08-26 17:24 UTC, ddmesh approved these changes

2022-03-11 09:36 UTC, pombredanne approved these changes
LGTM... merging at last!

2022-03-11 09:36 UTC, merged